---
abstract: 'a solver for ABC Path'
author:
  - 'Shlomi Fish <shlomif@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
keywords:
  - abc
  - game
  - games
  - grid
  - letters
  - path
  - puzzle
  - puzzles
  - riddle
  - riddles
  - table
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Games-ABC_Path-Solver
provides:
  Games::ABC_Path::Solver:
    file: lib/Games/ABC_Path/Solver.pm
    version: v0.0.1
  Games::ABC_Path::Solver::Base:
    file: lib/Games/ABC_Path/Solver/Base.pm
    version: v0.0.1
  Games::ABC_Path::Solver::Board:
    file: lib/Games/ABC_Path/Solver/Board.pm
    version: 0.01
  Games::ABC_Path::Solver::Move:
    file: lib/Games/ABC_Path/Solver/Move.pm
    version: v0.0.1
  Games::ABC_Path::Solver::Move::LastRemainingCellForLetter:
    file: lib/Games/ABC_Path/Solver/Move/LastRemainingCellForLetter.pm
    version: v0.0.1
  Games::ABC_Path::Solver::Move::LastRemainingLetterForCell:
    file: lib/Games/ABC_Path/Solver/Move/LastRemainingLetterForCell.pm
    version: v0.0.1
  Games::ABC_Path::Solver::Move::LettersNotInVicinity:
    file: lib/Games/ABC_Path/Solver/Move/LettersNotInVicinity.pm
    version: v0.0.1
  Games::ABC_Path::Solver::Move::ResultsInASuccess:
    file: lib/Games/ABC_Path/Solver/Move/ResultsInASuccess.pm
    version: v0.0.1
  Games::ABC_Path::Solver::Move::ResultsInAnError:
    file: lib/Games/ABC_Path/Solver/Move/ResultsInAnError.pm
    version: v0.0.1
  Games::ABC_Path::Solver::Move::TryingLetterForCell:
    file: lib/Games/ABC_Path/Solver/Move/TryingLetterForCell.pm
    version: v0.0.1
requires:
  Carp: 0
  Getopt::Long: 2.36
  base: 0
resources:
  homepage: http://www.shlomifish.org/open-source/projects/japanese-puzzle-games/abc-path/
  license: http://opensource.org/licenses/mit-license.php
  repository: http://svn.berlios.de/svnroot/repos/fc-solve/abc-path/
version: v0.0.1
